const Home = [
  {
    id: 1,
    title: "Extraction 2",
    img: "https://image.tmdb.org/t/p/w500/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
    rating: 8.1,
    genre: "Action",
  },
  {
    id: 2,
    title: "The Gray Man",
    img: "https://m.media-amazon.com/images/M/MV5BZmFhZTNlNzctZGQzZi00MTA3LThiNjMtYWQzNjUzMjNjZjA3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rating: 7.4,
    genre: "Thriller",
  },
  {
    id: 3,
    title: "Red Notice",
    img: "https://image.tmdb.org/t/p/w500/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
    rating: 7.6,
    genre: "Action",
  },
  {
    id: 4,
    title: "Enola Holmes 2",
    img: "https://image.tmdb.org/t/p/w500/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg",
    rating: 7.8,
    genre: "Mystery",
  },
  {
    id: 5,
    title: "The Adam Project",
    img: "https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    rating: 7.5,
    genre: "Sci-Fi",
  },
  {
    id: 6,
    title: "Inception",
    img: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    rating: 8.8,
    genre: "Sci-Fi",
  },
  {
    id: 7,
    title: "The Dark Knight",
    img: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    rating: 9.0,
    genre: "Action",
  },
  {
    id: 8,
    title: "Interstellar",
    img: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    rating: 8.6,
    genre: "Sci-Fi",
  },
  {
    id: 9,
    title: "Joker",
    img: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    rating: 8.5,
    genre: "Drama",
  },
  {
    id: 10,
    title: "Fight Club",
    img: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    rating: 8.8,
    genre: "Drama",
  },
  {
    id: 11,
    title: "Forrest Gump",
    img: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    rating: 8.9,
    genre: "Drama",
  },
  {
    id: 12,
    title: "The Shawshank Redemption",
    img: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    rating: 9.3,
    genre: "Drama",
  },
  {
    id: 13,
    title: "Avengers: Endgame",
    img: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    rating: 8.4,
    genre: "Action",
  },
  {
    id: 14,
    title: "Parasite",
    img: "https://play-lh.googleusercontent.com/cSbZZEeHvNVaLuGbj7tca5GSuTrGjNl_bTxJUrf0e4V54pntacCCALBPlNrXdGVg0UUfyLqQKoT-RzGGEnE",
    rating: 8.6,
    genre: "Thriller",
  },
  {
    id: 15,
    title: "Gladiator",
    img: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    rating: 8.5,
    genre: "Action",
  },
  {
    id: 16,
    title: "The Godfather",
    img: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    rating: 9.2,
    genre: "Drama",
  },
  {
    id: 17,
    title: "The Hangover",
    img: "https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
    rating: 7.7,
    genre: "Comedy",
  },
  {
    id: 18,
    title: "Superbad",
    img: "https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
    rating: 7.6,
    genre: "Comedy",
  },
  {
    id: 19,
    title: "Step Brothers",
    img: "https://m.media-amazon.com/images/I/51FIcCozbUL._AC_UF894,1000_QL80_.jpg",
    rating: 7.2,
    genre: "Comedy",
  },

  {
    id: 20,
    title: "Get Out",
    img: "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_.jpg",
    rating: 7.7,
    genre: "Horror",
  },
  {
    id: 21,
    title: "A Quiet Place",
    img: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    rating: 7.5,
    genre: "Horror",
  },
  {
    id: 22,
    title: "It",
    img: "https://image.tmdb.org/t/p/w500/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
    rating: 7.3,
    genre: "Horror",
  },

  {
    id: 23,
    title: "La La Land",
    img: "https://cdn.cinematerial.com/p/297x/unoktgtv/la-la-land-movie-poster-md.jpg?v=1472589717",
    rating: 8.0,
    genre: "Romance",
  },
  {
    id: 24,
    title: "The Notebook",
    img: "https://www.themoviedb.org/t/p/w1280/sYLiOOhcjnUdRt1MFgq56ZSMzzs.jpg",
    rating: 7.9,
    genre: "Romance",
  },
  {
    id: 25,
    title: "Pride & Prejudice",
    img: "https://www.themoviedb.org/t/p/w1280/wdWhRkt4cV9AaDO37cFFr9K1xQk.jpg",
    rating: 7.8,
    genre: "Romance",
  },
  {
    id: 26,
    title: "Avatar: The Way of Water",
    img: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    rating: 7.8,
    genre: "Sci-Fi",
  },
  {
    id: 27,
    title: "Guardians of the Galaxy",
    img: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    rating: 8.0,
    genre: "Action",
  },
  {
    id: 28,
    title: "Spider-Man: No Way Home",
    img: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    rating: 8.4,
    genre: "Action",
  },
  
  {
    id: 29,
    title: "Doctor Strange",
    img: "https://www.themoviedb.org/t/p/w1280/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg",
    rating: 7.5,
    genre: "Sci-Fi",
  },
  {
    id: 30,
    title: "Black Panther",
    img: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    rating: 7.3,
    genre: "Action",
  },
  {
    id: 31,
    title: "Mad Max: Fury Road",
    img: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    rating: 8.1,
    genre: "Action",
  },
  {
    id: 32,
    title: "John Wick",
    img: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    rating: 7.4,
    genre: "Thriller",
  },
  {
    id: 33,
    title: "Tenet",
    img: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
    rating: 7.3,
    genre: "Action",
  },
  {
    id: 34,
    title: "Skyfall",
    img: "https://i.pinimg.com/474x/25/5b/02/255b02262ef74228723fc79c87625abc.jpg",
    rating: 7.8,
    genre: "Thriller",
  },
  {
    id: 35,
    title: "Mission: Impossible – Fallout",
    img: "https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    rating: 8.0,
    genre: "Action",
  },
  {
    id: 36,
    title: "No Time to Die",
    img: "https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
    rating: 7.5,
    genre: "Thriller",
  },
  {
    id: 37,
    title: "The Bourne Ultimatum",
    img: "https://media-cache.cinematerial.com/p/500x/e4cypaxz/the-bourne-ultimatum-british-dvd-movie-cover.jpg?v=1456244046",
    rating: 8.0,
    genre: "Action",
  },
  {
    id: 38,
    title: "Taken",
    img: "https://lumiere-a.akamaihd.net/v1/images/image_efeee89d.jpeg?region=0%2C0%2C800%2C1200",
    rating: 7.8,
    genre: "Thriller",
  },
  {
    id: 39,
    title: "The Equalizer",
    img: "https://cdn.displate.com/artwork/857x1200/2023-11-19/7fab64baee160a35321b9bef791bdf0d_c951fce44b68569c7dcee081c52bcbfa.jpg",
    rating: 7.2,
    genre: "Action",
  },
  {
    id: 40,
    title: "Wrath of Man",
    img: "https://image.tmdb.org/t/p/w500/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
    rating: 7.1,
    genre: "Thriller",
  },
  {
    id: 41,
    title: "The Pianist",
    img: "https://images.moviesanywhere.com/83be0db16d401bf62ecab4c4f8568a4b/a4d71c78-9856-49ef-abd3-db245d6b484f.jpg",
    rating: 8.6,
    genre: "Drama",
  },
  {
    id: 42,
    title: "A Beautiful Mind",
    img: "https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
    rating: 8.2,
    genre: "Drama",
  },
  {
    id: 43,
    title: "Shutter Island",
    img: "https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
    rating: 8.1,
    genre: "Drama",
  },
  {
    id: 44,
    title: "The Pursuit of Happyness",
    img: "https://image.tmdb.org/t/p/w500/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    rating: 8.0,
    genre: "Drama",
  },
  {
    id: 45,
    title: "The Green Mile",
    img: "https://m.media-amazon.com/images/S/pv-target-images/d549752199de2bf343b9996ee3e703d7f372d1083e20c6a972a795bc69d9e066.jpg",
    rating: 9.0,
    genre: "Drama",
  },
  {
    id: 46,
    title: "Whiplash",
    img: "https://m.media-amazon.com/images/S/pv-target-images/124df3b92ceed98bbd0dbb0a786e097d25686706f5521a2c4f4d48586d41a556.jpg",
    rating: 8.5,
    genre: "Drama",
  },
  {
    id: 47,
    title: "The Social Network",
    img: "https://media-cache.cinematerial.com/p/500x/5ec8qonh/the-social-network-movie-poster.jpg?v=1456826391",
    rating: 7.7,
    genre: "Drama",
  },
  {
    id: 48,
    title: "The Imitation Game",
    img: "https://image.tmdb.org/t/p/w500/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
    rating: 8.0,
    genre: "Drama",
  },
  {
    id: 49,
    title: "The Revenant",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScyJL68sQ70Y7_B3f-D1MGLd7b4zjEFCxW6Q&s",
    rating: 8.0,
    genre: "Drama",
  },
  {
    id: 50,
    title: "Django Unchained",
    img: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    rating: 8.4,
    genre: "Drama",
  },
  {
    id: 51,
    title: "22 Jump Street",
    img: "https://media-cache.cinematerial.com/p/500x/wnmov9vo/22-jump-street-movie-poster.jpg?v=1456433262",
    rating: 7.0,
    genre: "Comedy",
  },
  {
    id: 52,
    title: "Central Intelligence",
    img: "https://m.media-amazon.com/images/M/MV5BMjA2NzEzNjIwNl5BMl5BanBnXkFtZTgwNzgwMTEzNzE@._V1_.jpg",
    rating: 6.8,
    genre: "Comedy",
  },
  {
    id: 53,
    title: "The Dictator",
    img: "https://m.media-amazon.com/images/M/MV5BM2IwMDM3ZmQtNjQ3NS00OTFiLWI5YzEtYWE3YjI5NTk3YzkwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rating: 6.7,
    genre: "Comedy",
  },
  {
    id: 54,
    title: "Yes Man",
    img: "https://image.tmdb.org/t/p/original/7aZAL3GuMqmHMt9iZ0G8E7q03uI.jpg",
    rating: 6.8,
    genre: "Comedy",
  },
  {
    id: 55,
    title: "Ted",
    img: "https://media-cache.cinematerial.com/p/500x/iuqrlqnp/ted-movie-poster.jpg?v=1456529027",
    rating: 7.0,
    genre: "Comedy",
  },
  {
    id: 56,
    title: "We're the Millers",
    img: "https://image.tmdb.org/t/p/original/qF2LJ0jwWrtXSuT4AFD5OS2IqaT.jpg",
    rating: 7.0,
    genre: "Comedy",
  },
  {
    id: 57,
    title: "Crazy Rich Asians",
    img: "https://image.tmdb.org/t/p/w500/1XxL4LJ5WHdrcYcihEZUCgNCpAW.jpg",
    rating: 7.1,
    genre: "Comedy",
  },
  {
    id: 58,
    title: "Pitch Perfect",
    img: "https://image.tmdb.org/t/p/original/ntRIoh8Qf1BI1AYGx0STfq0wUmb.jpg",
    rating: 7.1,
    genre: "Comedy",
  },
  {
    id: 59,
    title: "The Intouchables",
    img: "https://image.tmdb.org/t/p/original/323BP0itpxTsO0skTwdnVmf7YC9.jpg",
    rating: 8.5,
    genre: "Comedy",
  },
  {
    id: 60,
    title: "The Internship",
    img: "https://image.tmdb.org/t/p/original/upKBIpfjIrAj5KaTCAPoIC7JnyL.jpg",
    rating: 6.5,
    genre: "Comedy",
  },
  {
    id: 61,
    title: "The Conjuring",
    img: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    rating: 7.5,
    genre: "Horror",
  },
  {
    id: 62,
    title: "Hereditary",
    img: "https://m.media-amazon.com/images/S/pv-target-images/2be98bed028f1d53e01a860b6bb91c362dc32611c45effbcf2aa2645d590b22a.jpg",
    rating: 7.2,
    genre: "Horror",
  },
  {
    id: 63,
    title: "The Nun",
    img: "https://image.tmdb.org/t/p/w500/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg",
    rating: 6.4,
    genre: "Horror",
  },
  {
    id: 64,
    title: "Annabelle",
    img: "https://images.moviesanywhere.com/9bb79302cc5390cf15c9b61bace4cc6d/6cfdbb63-d7f9-4625-b000-4648e905ed38.jpg",
    rating: 5.7,
    genre: "Horror",
  },
  {
    id: 65,
    title: "Insidious",
    img: "https://m.media-amazon.com/images/S/pv-target-images/a311d626796e53a03cebd7241088cd74389a7940e10de7bfeabf46f73a80d91d.jpg",
    rating: 6.8,
    genre: "Horror",
  },
  {
    id: 66,
    title: "The Ring",
    img: "https://media-cache.cinematerial.com/p/500x/ynmb4lbl/the-ring-movie-poster.jpg?v=1456279183",
    rating: 7.0,
    genre: "Horror",
  },
  {
    id: 67,
    title: "Lights Out",
    img: "https://media-cache.cinematerial.com/p/500x/7gxnjujd/lights-out-dvd-movie-cover.jpg?v=1469454295",
    rating: 6.3,
    genre: "Horror",
  },
  {
    id: 68,
    title: "Smile",
    img: "https://media-cache.cinematerial.com/p/500x/jcecuchr/smile-movie-poster.jpg?v=1660669798",
    rating: 6.8,
    genre: "Horror",
  },
  {
    id: 69,
    title: "The Babadook",
    img: "https://upload.wikimedia.org/wikipedia/en/d/d7/The-Babadook-Poster.jpg",
    rating: 6.8,
    genre: "Horror",
  },
  {
    id: 70,
    title: "Midsommar",
    img: "https://m.media-amazon.com/images/S/pv-target-images/3d493cdebe7629f475205fe095cd89b17529fb7e2664505be2a81ffedd802aac.jpg",
    rating: 7.1,
    genre: "Horror",
  },
  {
    id: 71,
    title: "Titanic",
    img: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    rating: 8.0,
    genre: "Romance",
  },
  {
    id: 72,
    title: "Me Before You",
    img: "https://lh4.googleusercontent.com/proxy/OcU8KOpFMYkUnEK4QfJaIAohwpilupmmq8nj0QVNd2y_a2O24LO1xSQB1vDcw3ztDhXCT_YZ-daB3raK3fuISispPorPAU4v0SVbxK6w",
    rating: 7.4,
    genre: "Romance",
  },
  {
    id: 73,
    title: "The Fault in Our Stars",
    img: "https://lh5.googleusercontent.com/proxy/SyZoGwUR3K_a-0ItnJiijA54_D39KeQK_Y7gmXzFUJjpfPqlRg2jnMteviB6C7HnQ3Jw_PiBGm1LXNt93uJNwKDhqqDXT1cfWp5ABgjzOOhGasQ",
    rating: 7.6,
    genre: "Romance",
  },
  {
    id: 74,
    title: "Call Me by Your Name",
    img: "https://image.tmdb.org/t/p/original/gXiE0WveDnT0n5J4sW9TMxXF4oT.jpg",
    rating: 8.0,
    genre: "Romance",
  },
  {
    id: 75,
    title: "Before Sunrise",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkG4Q0ibIbDEXT5tvNI52sW3QFH7C2uQTe7A&s",
    rating: 8.1,
    genre: "Romance",
  },
  {
    id: 76,
    title: "The Vow",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1NvSZd7jbLMhdpCeGMeviSEITvHi6_5S4Tg&s",
    rating: 7.0,
    genre: "Romance",
  },
  {
    id: 77,
    title: "500 Days of Summer",
    img: "https://bananaroad.com/cdn/shop/products/pst0441dl_large.jpeg?v=1464449098",
    rating: 7.7,
    genre: "Romance",
  },
  {
    id: 78,
    title: "About Time",
    img: "https://i.pinimg.com/564x/39/45/60/394560b59cd31de7b2c6fd30ff7cc253.jpg",
    rating: 8.1,
    genre: "Romance",
  },
  {
    id: 79,
    title: "The Shape of Water",
    img: "https://i.pinimg.com/474x/ab/98/d2/ab98d2a0abefa7ad0c369f8084809872.jpg",
    rating: 7.4,
    genre: "Romance",
  },
  {
    id: 80,
    title: "To All the Boys I've Loved Before",
    img: "https://image.tmdb.org/t/p/original/hKHZhUbIyUAjcSrqJThFGYIR6kI.jpg",
    rating: 7.2,
    genre: "Romance",
  },
  {
    id: 81,
    title: "The Matrix",
    img: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    rating: 8.7,
    genre: "Sci-Fi",
  },
  {
    id: 82,
    title: "Dune",
    img: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    rating: 8.0,
    genre: "Sci-Fi",
  },
  {
    id: 83,
    title: "Arrival",
    img: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    rating: 7.9,
    genre: "Sci-Fi",
  },
  {
    id: 84,
    title: "The Martian",
    img: "https://resizing.flixster.com/-n4CxtT8pz1lZXdiS4kfvZbWGNA=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10980706_k_v10_ab.jpg",
    rating: 8.0,
    genre: "Sci-Fi",
  },
  {
    id: 85,
    title: "Edge of Tomorrow",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJZiymBaCZrJHD5fWhYs6jmYln4Uj6Q2xsdINt_FHwVxAGLDa3_Mr2D-senBc1bhmTqYg&usqp=CAU",
    rating: 7.9,
    genre: "Sci-Fi",
  },
  {
    id: 86,
    title: "Oblivion",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXjOTulrZJ65FXJXTEdfBkbaunl2RB4XDGrN0M8M3lXjRIzc6Wt-44WF7FccV2HmDyMPc&usqp=CAU",
    rating: 7.1,
    genre: "Sci-Fi",
  },
  {
    id: 87,
    title: "Ex Machina",
    img: "https://image.tmdb.org/t/p/original/3KnL9sztQAP2lmiU6ZdGbdYu3Pu.jpg",
    rating: 7.7,
    genre: "Sci-Fi",
  },
  {
    id: 88,
    title: "Looper",
    img: "https://cdn.hollywoodsuite.ca/fit-in/462x710/filters:format(webp)/wp-content/uploads/poster-2000x3000/HS904356_poster_2000_3000.jpg",
    rating: 7.4,
    genre: "Sci-Fi",
  },
  {
    id: 89,
    title: "Snowpiercer",
    img: "https://upload.wikimedia.org/wikipedia/en/b/b4/Snowpiercer_poster.jpg",
    rating: 7.3,
    genre: "Sci-Fi",
  },
  {
    id: 90,
    title: "Ready Player One",
    img: "https://image.tmdb.org/t/p/w500/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
    rating: 7.6,
    genre: "Sci-Fi",
  },
  {
    id: 91,
    title: "Frozen",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyigtEP7shCN1Lfx6SLMc6sa_6A444sEziOQ&s",
    rating: 7.3,
    genre: "Animation",
  },
  {
    id: 92,
    title: "Coco",
    img: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    rating: 8.4,
    genre: "Animation",
  },
  {
    id: 93,
    title: "Minions",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9caKwE-w7Iya3Thph-ln6HqLpz-vzYAuA0A&s",
    rating: 6.7,
    genre: "Animation",
  },
  {
    id: 94,
    title: "Inside Out",
    img: "https://image.tmdb.org/t/p/w500/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg",
    rating: 8.1,
    genre: "Animation",
  },
  {
    id: 95,
    title: "Toy Story 4",
    img: "https://image.tmdb.org/t/p/w500/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
    rating: 7.8,
    genre: "Animation",
  },
  {
    id: 96,
    title: "Moana",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_abQ60OOW7nubUfy5QWEChSopsKGhneMKOw&s",
    rating: 7.6,
    genre: "Animation",
  },
  {
    id: 97,
    title: "Ratatouille",
    img: "https://image.tmdb.org/t/p/w500/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg",
    rating: 8.1,
    genre: "Animation",
  },
  {
    id: 98,
    title: "The Lion King",
    img: "https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
    rating: 8.5,
    genre: "Animation",
  },
  {
    id: 99,
    title: "Zootopia",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzI-aXWxJ9T3p5_U3a8Azag738uuDLr028Q&s",
    rating: 8.0,
    genre: "Animation",
  },
  {
    id: 100,
    title: "Up",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP73UK3y4ojhMytnmkr2VBdErOlG8DIjZySA&s",
    rating: 8.2,
    genre: "Animation",
  },

  {
    id: 101,
    title: "Knives Out",
    img: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    rating: 7.9,
    genre: "Mystery",
  },
  {
    id: 102,
    title: "Gone Girl",
    img: "https://image.tmdb.org/t/p/w500/qymaJhucquUwjpb8oiqynMeXnID.jpg",
    rating: 8.1,
    genre: "Thriller",
  },
  {
    id: 103,
    title: "Se7en",
    img: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    rating: 8.6,
    genre: "Thriller",
  },
  {
    id: 104,
    title: "Oldboy",
    img: "https://s3.amazonaws.com/nightjarprod/content/uploads/sites/216/2023/08/17120049/OLDBOY-Final-Poster-691x1024.jpeg",
    rating: 8.4,
    genre: "Thriller",
  },
  {
    id: 105,
    title: "The Prestige",
    img: "https://images.moviesanywhere.com/4d9df0e6b0bd732b3d1fa967b5b919fa/1adaca39-ae5e-4867-91fd-6025d3d08eb4.jpg",
    rating: 8.5,
    genre: "Drama",
  },
  {
    id: 106,
    title: "The Wolf of Wall Street",
    img: "https://image.tmdb.org/t/p/w500/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
    rating: 8.2,
    genre: "Drama",
  },
  {
    id: 107,
    title: "1917",
    img: "https://www.tallengestore.com/cdn/shop/products/1917_-_Sam_Mendes_-_Hollywood_War_Film_Classic_English_Movie_Poster_8ebc60d6-7299-4918-80db-989d0f188018.jpg?v=1582781093",
    rating: 8.3,
    genre: "Drama",
  },
  {
    id: 108,
    title: "The Curious Case of Benjamin Button",
    img: "https://lh3.googleusercontent.com/proxy/B9xO54viSeJ22U9rCDyMOIhDzChVsoUJTVMo17h2F3Bs2VO9FKV9HyJg7qkuKBJCcWdhYtAg7LjHSvcVexh_qUuP5LJaDeCf0Y5efjU56xcQEzOcdAQRjJIL_zGkQu-rPXtttNY",
    rating: 7.8,
    genre: "Drama",
  },
  {
    id: 109,
    title: "Cast Away",
    img: "https://cdn.displate.com/artwork/857x1200/2021-05-07/48d1a7d9b6d89f797e775a1bd26d02d9_918048808dea8de9825b9c908933fdde.jpg",
    rating: 7.8,
    genre: "Drama",
  },
  {
    id: 110,
    title: "The Truman Show",
    img: "https://i.pinimg.com/736x/b8/1f/dd/b81fdd8ab331df890c8617c0b3ccfcc6.jpg",
    rating: 8.2,
    genre: "Drama",
  },
  {
    id: 111,
    title: "Baby Driver",
    img: "https://m.media-amazon.com/images/I/71jVC2oq4JL._AC_UF894,1000_QL80_.jpg",
    rating: 7.6,
    genre: "Action",
  },
  {
    id: 112,
    title: "Deadpool",
    img: "https://image.tmdb.org/t/p/w500/zq8Cl3PNIDGU3iWNRoc5nEZ6pCe.jpg",
    rating: 8.0,
    genre: "Action",
  },
  {
    id: 113,
    title: "Logan",
    img: "https://i.ebayimg.com/00/s/MTYwMFgxMDM4/z/IgYAAOSwBr1kXLCG/$_57.JPG?set_id=880000500F",
    rating: 8.1,
    genre: "Action",
  },
  {
    id: 114,
    title: "The Hunger Games",
    img: "https://m.media-amazon.com/images/M/MV5BMWI1OGM4YjQtNmIxNi00YmE2LWJkNTAtY2Q0YjU4NTI5NWQyXkEyXkFqcGc@._V1_.jpg",
    rating: 7.3,
    genre: "Action",
  },
  {
    id: 115,
    title: "The Terminal",
    img: "https://media-cache.cinematerial.com/p/500x/rytbme5n/the-terminal-movie-cover.jpg?v=1456857392",
    rating: 7.3,
    genre: "Drama",
  },
  {
    id: 116,
    title: "Life of Pi",
    img: "https://artofthemovies.co.uk/cdn/shop/products/life_of_pi_intl_styleA_SD14590_B-311858_1024x1024@2x.jpg?v=1613508221",
    rating: 7.8,
    genre: "Drama",
  },
  {
    id: 117,
    title: "The Grand Budapest Hotel",
    img: "https://i.pinimg.com/474x/bf/5e/a0/bf5ea0be3e0e29ae61a00ba049dda0d0.jpg",
    rating: 8.1,
    genre: "Comedy",
  },
  {
    id: 118,
    title: "La Haine",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2gvX54UDl6FvjVPMdx9_JLEuIfbtFk-_qfQ&s",
    rating: 8.1,
    genre: "Drama",
  },
  {
    id: 119,
    title: "Jojo Rabbit",
    img: "https://image.tmdb.org/t/p/w500/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
    rating: 7.9,
    genre: "Comedy",
  },
  {
    id: 120,
    title: "The Big Short",
    img: "https://c8.alamy.com/comp/2RJ4RE7/the-big-short-2015-directed-by-adam-mckay-credit-plan-b-entertainmentregency-enterprises-album-2RJ4RE7.jpg",
    rating: 7.8,
    genre: "Drama",
  },
  {
    id: 121,
    title: "Ford v Ferrari",
    img: "https://www.tallengestore.com/cdn/shop/products/Ford_Vs_Ferrari_-_Christian_Bale_-_Matt_Damon_-_Le_Mans_66_-_Hollywood_English_Action_Movie_Poster_d283ff9c-c41d-43d4-8c93-a582365507ab.jpg?v=1583299941",
    rating: 8.1,
    genre: "Drama",
  },
  {
    id: 122,
    title: "Hacksaw Ridge",
    img: "https://m.media-amazon.com/images/M/MV5BMjQ1NjM3MTUxNV5BMl5BanBnXkFtZTgwMDc5MTY5OTE@._V1_.jpg",
    rating: 8.1,
    genre: "Action",
  },
  {
    id: 123,
    title: "War Dogs",
    img: "https://m.media-amazon.com/images/M/MV5BYjZiYTQxZTItY2Q2YS00MjM4LWFkMzQtZTRmNDg0NjE3YzU0XkEyXkFqcGc@._V1_.jpg",
    rating: 7.1,
    genre: "Comedy",
  },
  {
    id: 124,
    title: "Uncharted",
    img: "https://media-cache.cinematerial.com/p/500x/9p2p3ux7/uncharted-movie-poster.jpg?v=1646088223",
    rating: 6.7,
    genre: "Action",
  },
  {
    id: 125,
    title: "Top Gun: Maverick",
    img: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    rating: 8.3,
    genre: "Action",
  },
  {
    id: 126,
    title: "The Menu",
    img: "https://m.media-amazon.com/images/M/MV5BMzllNzNmMTUtYTc2ZC00MGE5LWI3NjItY2EyZTM0YjhjNmU3XkEyXkFqcGc@._V1_.jpg",
    rating: 7.3,
    genre: "Thriller",
  },
  {
    id: 127,
    title: "Everything Everywhere All at Once",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-viJdd07RWsNZW3QjuCKIvSvRE_oRo9ht0w&s",
    rating: 8.0,
    genre: "Sci-Fi",
  },
  {
    id: 128,
    title: "Smile 2",
    img: "https://image.tmdb.org/t/p/original/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
    rating: 7.0,
    genre: "Horror",
  },
  {
    id: 129,
    title: "Oppenheimer",
    img: "https://www.hollywoodreporter.com/wp-content/uploads/2022/07/Oppenheimer-Movie-Poster-Universal-Publicity-EMBED-2022-.jpg?w=1000",
    rating: 8.5,
    genre: "Drama",
  },
  {
    id: 130,
    title: "Barbie",
    img: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    rating: 7.0,
    genre: "Comedy",
  }, {
    id: 131,
    title: "Spider-Man: Across the Spider-Verse",
    img: "https://i.pinimg.com/736x/d7/d3/5c/d7d35c40aa5bf6d2cf925b2757b07837.jpg",
    rating: 9.2,
    genre: "Animation",
    year: 2023
  },
];

export default Home;
